# Use the official python image from the docker hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any packages specified in requirements.txt
RUN pip install flask

# Make port 5000 avaiable to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]